import { motion } from 'framer-motion'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionHeader from '../components/SectionHeader'
import CtaSection from '../sections/CtaSection'
import { benefits, industries, serviceGroups } from '../data/siteData'

export default function Home() { return <>
  <section className="overflow-hidden bg-gradient-to-br from-white via-blue-50 to-orange-50 py-20 lg:py-28"><div className="container-site grid items-center gap-12 lg:grid-cols-2"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><p className="eyebrow">Your Trusted Compliance Partner</p><h1 className="font-heading text-5xl font-bold leading-tight tracking-tight text-slate-950 sm:text-6xl">Compliance Made <span className="text-brand">Simple.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Helping businesses achieve Indian and international regulatory certifications with confidence.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/contact" className="btn-primary gap-2">Get Consultation <ArrowRight size={18} /></Link><Link to="/services" className="btn-secondary">Our Services</Link></div></motion.div><div className="relative mx-auto w-full max-w-lg"><div className="absolute inset-8 rounded-full bg-blue-200/50 blur-3xl" /><div className="relative card grid gap-4 !p-8"><p className="font-heading text-xl font-semibold">Your path to market access</p>{['Requirement assessment', 'Testing & documentation', 'Application management', 'Approval & ongoing compliance'].map((x,i) => <div key={x} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 font-semibold text-brand">{i+1}</span><span className="font-medium">{x}</span></div>)}</div></div></div></section>
  <section className="section"><div className="container-site"><SectionHeader eyebrow="Our Expertise" title="Compliance support across every market" text="An integrated portfolio designed for manufacturers, importers, exporters and brands." centered /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{serviceGroups.map(group => { const Icon=group.icon; return <Link to="/services" className="card" key={group.title}><Icon className="text-brand" size={30}/><h3 className="mt-5 text-xl font-semibold">{group.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{group.services.length} focused service areas with end-to-end guidance.</p></Link>})}</div></div></section>
  <section className="section bg-slate-50"><div className="container-site"><SectionHeader eyebrow="How It Works" title="A clear compliance journey" centered /><div className="mt-12 grid gap-6 md:grid-cols-4">{['Assess', 'Prepare', 'Coordinate', 'Certify'].map((x,i)=><div className="text-center" key={x}><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-brand font-bold text-white">0{i+1}</span><h3 className="mt-4 text-lg font-semibold">{x}</h3><p className="mt-2 text-sm text-slate-600">{['Identify standards and the correct approval route.','Organize samples, documents and technical files.','Manage testing, submissions and authority follow-ups.','Secure approval and maintain ongoing compliance.'][i]}</p></div>)}</div></div></section>
  <section className="section"><div className="container-site"><SectionHeader eyebrow="Industries" title="Specialist knowledge for diverse products" /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{industries.map(({name,icon:Icon,text})=><article className="card" key={name}><Icon className="text-brand"/><h3 className="mt-4 text-lg font-semibold">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
  <section className="section bg-blue-50/70"><div className="container-site grid gap-10 lg:grid-cols-2"><div><SectionHeader eyebrow="Why SNN" title="Confidence at every compliance milestone" text="We translate complex requirements into a practical, transparent plan for your team."/><div className="mt-7 space-y-3">{['Responsive, expert-led support','Transparent scope and progress updates','Multi-standard, multi-market capability','Built around your commercial timelines'].map(x=><p key={x} className="flex gap-3 text-slate-700"><CheckCircle2 className="shrink-0 text-green-500" size={21}/>{x}</p>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{benefits.map(({title,text,icon:Icon})=><article className="card" key={title}><Icon className="text-accent"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
  <CtaSection />
</> }
